server:
  port: 8089


spring:
  application:
    name: APPLICATION-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/application_service_db
    username: postgres
    password: doni2045
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

eureka:
  client:
    service-url:
      defaultUrl : ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true
